### ISSUE TITLE
Screenshot feature broken with provider on localhost

### ISSUE THREAD

**Issue by Kous92** [DeviceFarmer/stf_ios_support#48]
Hello,

For the iOS extension of OpenSTF, me and @chriis78 are working to see if some features that works for Android can work on iOS. I have in mind the screenshot feature.

Actually, I have seen that screenshot feature does not display the output on the webpage like Android, but saves an image of the screenshot only on `repos/stf-ios-provider/<udid>.jpg`

The image is saved even if I don't have the video output on STF web interface like below.

![Capture d’écran 2020-05-22 à 01 40 54](https://user-images.githubusercontent.com/15252166/82616416-6e56ba80-9bcd-11ea-9fde-9bf682413c01.png)

This is the output on `./view_logs -proc stf_device_ios`
```
2020-05-21T23:34:41.508Z INF/ios-device:plugins:screen:capture 6726 [9*********8] Capturing screenshot
2020-05-21T23:34:44.301Z ERR/device:support:storage 6726 [9*********8] Upload to "https://localhost:7100/s/upload/blob" failed FetchError: request to https://localhost:7100/s/upload/blob failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/kous/STF/stf_ios_support/repos/stf-ios-provider/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:322:22)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:6726) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at /Users/kous/STF/stf_ios_support/repos/stf-ios-provider/lib/units/device/support/storage.js:44:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
2020-05-21T23:34:44.317Z ERR/ios-device:plugins:screen:capture 6726 [9*********8] Screen capture failed FetchError: request to https://localhost:7100/s/upload/blob failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/kous/STF/stf_ios_support/repos/stf-ios-provider/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:322:22)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

As I understand, it does not accept the http localhost. Any idea for the implementation ?

**Comment by nanoscopic** [comment]
This is working when stf-ios-provider is bound to a real network address and not localhost. I have never tested or attempted to make it work with localhost. I agree that is likely the issue.

It isn't that it "needs to be implemented". You have found a bug when it is run on localhost.

**Comment by Kous92** [comment]
@nanoscopic I confirm you that it works only if the STF server side is secured with HTTPS, I have tried it with the included Docker configuration. The stf-ios-provider needs I think to have a block like the video stream to use the http protocol if STF is in http, or https if STF in in https.

**Comment by chriiis78** [comment]
I changed the agent in `repos/stf-ios-provider/lib/units/device/support/storage.js`:
```
      var postUrl = url.resolve(options.storageUrl, util.format('s/upload/%s', type))
      var resolvedUrl = new URL(postUrl)

      var agent = null
      const agentParam = {
        rejectUnauthorized: false,
        method: 'POST'
      }
      if (resolvedUrl.protocol == 'http:') {
        agent = new http.Agent( agentParam )
      }
      else {
        agent = new https.Agent( agentParam )
      }
```
Now, it works in http and https.

**Comment by Kous92** [comment]
@nanoscopic I definitely recommend you to modify storage.js with this code on the `module.exports = syrup.serial()`. Also by adding on the headers `var http = require('http')`. With that, the screenshot feature on iOS with STF is fully supported in HTTP and HTTPS. I have tested myself the code suggestion of @chriiis78, and it works.

**Comment by nanoscopic** [comment]
Solution looks good. I will add it. I still remain not a fan of plain http; but :shrug: I'd rather add code supporting it than have a philosophical debate about http/https.

**Comment by nanoscopic** [comment]
I've changed my mind on this. Plain http will not be supported. HTTPS everywhere is the way the world has gone and so should anyone using plain http. Closing. All plain http related tickets will be closed from here on out.
