### ISSUE TITLE
can't use the latest commit to run 

### ISSUE THREAD

**Issue by chaooe** [DeviceFarmer/stf_ios_support#91]
i am using the lastest commit https://github.com/DeviceFarmer/stf_ios_support/commit/240875c31245b7064a17c23b2b91477aad091ca1
but failed to run as below
![图片](https://user-images.githubusercontent.com/12910117/102866823-d70f5980-4472-11eb-8ae8-9945c6e84fc6.png)

```
INFO[0001] ideviceinfo call                              ops="[-u 00008030-001969593ADB802E -k ProductVersion]" type=ilib_getinfo_call
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43bfa07]

goroutine 1 [running]:
main.NewRunningDev(0xc0002a2380, 0xc000283350, 0xc00029b3e0, 0xc0002834a0, 0xc000272025, 0x19, 0xc0002b40f8)
        /Users/alexzhao/Work/Archs/stf_ios_support/coordinator/coordinator.go:508 +0x307
main.event_loop(0xc0002a2380, 0xc00029b8f0, 0xe, 0xc0002961e0, 0xc0002804e0, 0xc00028e59c, 0x3, 0xc000296180, 0xc000283350, 0xc00029b3e0, ...)
        /Users/alexzhao/Work/Archs/stf_ios_support/coordinator/coordinator.go:619 +0x31bb
main.main()
        /Users/alexzhao/Work/Archs/stf_ios_support/coordinator/coordinator.go:422 +0x1511
E: 20-12-22 16:28:11 [52721]dangling 'REP' socket created at :336
E: 20-12-22 16:28:11 [52721]dangling 'PULL' socket created at :152
E: 20-12-22 16:28:11 [52721]dangling 'PUB' socket created at :28
```

**Comment by chaooe** [comment]
fixed . it need to add devices in th config.json file as below.

```
},
  "video": {
    "enabled": false,
    "use_vnc": false,
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 5
  },
  "devices": [
  ],
  "install": {
    "root_path": "",
    "config_path": "./config.json",
    "set_working_dir": false
  },
```

**Comment by nanoscopic** [comment]
This commit also fixes this issue: https://github.com/DeviceFarmer/stf_ios_support/commit/5d5f3e7ec95f2e74e8c9a4f5df75785c3c6a6504

This was the intent to begin with; it should function even without devices being set in config. Thanks for making a ticket for this to quickly bring it to my attention.
